export const initialData = {
  customers: [
    {
      id: "c1",
      name: "Creation Gardens",
      email: "",
      phone: "",
      accountNumber: "",
      status: "Active",
      billingAddress: "",
      billingTerms: "",
      xeroContactId: "",
      notes: "",
      locations: ["l1"],
      workOrders: [],
    },
    {
      id: "c2",
      name: "Walmart",
      email: "",
      phone: "",
      accountNumber: "",
      status: "Active",
      billingAddress: "",
      billingTerms: "",
      xeroContactId: "",
      notes: "",
      locations: ["l2"],
      workOrders: [],
    },
    {
      id: "c3",
      name: "Hilton Downtown",
      email: "",
      phone: "",
      accountNumber: "",
      status: "Active",
      billingAddress: "",
      billingTerms: "",
      xeroContactId: "",
      notes: "",
      locations: ["l3"],
      workOrders: ["wo3"],
    },
    {
      id: "c4",
      name: "test flow customer 1",
      email: "",
      phone: "",
      accountNumber: "",
      status: "Active",
      billingAddress: "",
      billingTerms: "",
      xeroContactId: "",
      notes: "",
      locations: ["l4"],
      workOrders: ["wo4"],
    },
    {
      id: "c5",
      name: "test wo flow 2",
      email: "",
      phone: "",
      accountNumber: "",
      status: "Active",
      billingAddress: "",
      billingTerms: "",
      xeroContactId: "",
      notes: "",
      locations: [],
      workOrders: [],
    },
    {
      id: "c6",
      name: "test flow 3",
      email: "xyz@gmail.com",
      phone: "(564) 546-5465",
      accountNumber: "546546546",
      status: "Active",
      billingAddress: "",
      billingTerms: "Net 15",
      xeroContactId: "546546",
      notes: "",
      locations: ["l5"],
      workOrders: ["wo5"],
    },
    {
      id: "c7",
      name: "test flow 4",
      email: "test@gmail.com",
      phone: "+53 45 35345",
      accountNumber: "",
      status: "Active",
      billingAddress: "",
      billingTerms: "",
      xeroContactId: "",
      notes: "",
      locations: [],
      workOrders: ["wo6"],
    },
    {
      id: "c8",
      name: "GCO Test",
      email: "gloria@tuesdaywiz.com",
      phone: "0989",
      accountNumber: "",
      status: "Active",
      billingAddress: "",
      billingTerms: "",
      xeroContactId: "",
      notes: "",
      locations: [],
      workOrders: [],
    },
    {
      id: "c9",
      name: "Test WO 4",
      email: "gloria@tuesdaywiz.com",
      phone: "688448",
      accountNumber: "6789999",
      status: "Active",
      billingAddress: "",
      billingTerms: "",
      xeroContactId: "",
      notes: "",
      locations: [],
      workOrders: ["wo7"],
    },
    {
      id: "c10",
      name: "Glory",
      email: "glory@tuesdaywiz.com",
      phone: "",
      accountNumber: "789000",
      status: "Active",
      billingAddress: "",
      billingTerms: "",
      xeroContactId: "",
      notes: "",
      locations: ["l6"],
      workOrders: ["wo8"],
    },
    {
      id: "c11",
      name: "test -03",
      email: "",
      phone: "",
      accountNumber: "",
      status: "Active",
      billingAddress: "",
      billingTerms: "",
      xeroContactId: "",
      notes: "",
      locations: [],
      workOrders: ["wo9"],
    },
  ],
  locations: [
    {
      id: "l1",
      name: "Creation Gardens – Warehouse",
      streetAddress: "",
      city: "",
      state: "",
      zip: "",
      status: "Active",
      notes: "",
      customerId: "c1",
      workOrders: [],
      equipments: ["eq2"],
    },
    {
      id: "l2",
      name: "Walmart Store #210",
      streetAddress: "",
      city: "",
      state: "",
      zip: "",
      status: "Active",
      notes: "",
      customerId: "c2",
      workOrders: [],
      equipments: ["eq1"],
    },
    {
      id: "l3",
      name: "Hilton Downtown – Kitchen",
      streetAddress: "",
      city: "",
      state: "",
      zip: "",
      status: "Active",
      notes: "",
      customerId: "c3",
      workOrders: ["wo3"],
      equipments: ["eq3"],
    },
    {
      id: "l4",
      name: "test flow location 1",
      streetAddress: "",
      city: "",
      state: "",
      zip: "",
      status: "Active",
      notes: "",
      customerId: "c4",
      workOrders: ["wo4"],
      equipments: [],
    },
    {
      id: "l5",
      name: "test wo location 2",
      streetAddress: "",
      city: "",
      state: "",
      zip: "",
      status: "Active",
      notes: "",
      customerId: "c6",
      workOrders: ["wo5"],
      equipments: [],
    },
    {
      id: "l6",
      name: "Test Location 6",
      streetAddress: "",
      city: "",
      state: "",
      zip: "",
      status: "Active",
      notes: "",
      customerId: "c10",
      workOrders: ["wo8"],
      equipments: [],
    },
  ],
  workOrders: [
    {
      id: "wo1",
      name: "Ice Machine Repair",
      customerId: null,
      locationId: null,
      description: "Ice machine not producing ice.",
      status: "Unscheduled",
      technicianId: null,
      scheduledDate: "2025-03-12",
      model: "T-49-HC",
      serialNumber: "",
      serviceHistory: "March 2025 – Compressor replaced",
      workPerformed: "Replaced evaporator fan motor.",
      equipmentId: "eq1",
      invoiceId: null,
      partsOrdered: "",
      photos: [],
      group: "active",
    },
    {
      id: "wo2",
      name: "Walk-in Freezer Install",
      customerId: null,
      locationId: null,
      description: "Customer reports loud noise.",
      status: "Parts Needed",
      technicianId: null,
      scheduledDate: "2025-03-05",
      model: "KM-901MAH",
      serialNumber: "SN-83749203",
      serviceHistory: "Jan 2026 – Fan motor replaced",
      workPerformed: "Tested system.",
      equipmentId: "eq2",
      invoiceId: null,
      partsOrdered: "",
      photos: [],
      group: "active",
    },
    {
      id: "wo3",
      name: "GCO",
      customerId: "c3",
      locationId: "l3",
      description: "",
      status: "Active",
      technicianId: "t1",
      scheduledDate: null,
      model: "",
      serialNumber: "",
      serviceHistory: "",
      workPerformed: "",
      equipmentId: null,
      invoiceId: "GCO",
      partsOrdered: "",
      photos: [],
      group: "active",
    },
    {
      id: "wo4",
      name: "test work order flow 1",
      customerId: "c4",
      locationId: "l4",
      description: "short narrative test about work to be performed...",
      status: "Unscheduled",
      technicianId: "t2",
      scheduledDate: "2025-03-11",
      model: "",
      serialNumber: "",
      serviceHistory: "",
      workPerformed: "",
      equipmentId: null,
      invoiceId: null,
      partsOrdered: "",
      photos: [],
      group: "active",
    },
    {
      id: "wo5",
      name: "test work order flow 2",
      customerId: "c6",
      locationId: "l5",
      description: "short narratibve",
      status: "Unscheduled",
      technicianId: "t2",
      scheduledDate: "2025-03-12",
      model: "",
      serialNumber: "",
      serviceHistory: "",
      workPerformed: "field tec narrtive after work complete",
      equipmentId: null,
      invoiceId: null,
      partsOrdered: "",
      photos: [],
      group: "active",
    },
    {
      id: "wo6",
      name: "test work order flow 3",
      customerId: "c7",
      locationId: null,
      description: "",
      status: "Unscheduled",
      technicianId: null,
      scheduledDate: null,
      model: "",
      serialNumber: "",
      serviceHistory: "",
      workPerformed: "",
      equipmentId: null,
      invoiceId: null,
      partsOrdered: "",
      photos: [],
      group: "active",
    },
    {
      id: "wo7",
      name: "Test WO 4",
      customerId: "c9",
      locationId: null,
      description: "",
      status: "Unscheduled",
      technicianId: null,
      scheduledDate: null,
      model: "",
      serialNumber: "",
      serviceHistory: "",
      workPerformed: "",
      equipmentId: null,
      invoiceId: null,
      partsOrdered: "",
      photos: [],
      group: "active",
    },
    {
      id: "wo8",
      name: "Test WO 6",
      customerId: "c10",
      locationId: "l6",
      description: "",
      status: "Unscheduled",
      technicianId: null,
      scheduledDate: null,
      model: "",
      serialNumber: "",
      serviceHistory: "",
      workPerformed: "",
      equipmentId: null,
      invoiceId: null,
      partsOrdered: "",
      photos: [],
      group: "active",
    },
    {
      id: "wo9",
      name: "Test 03",
      customerId: "c11",
      locationId: null,
      description: "",
      status: "Unscheduled",
      technicianId: null,
      scheduledDate: null,
      model: "",
      serialNumber: "",
      serviceHistory: "",
      workPerformed: "",
      equipmentId: null,
      invoiceId: null,
      partsOrdered: "",
      photos: [],
      group: "active",
    },
  ],
  technicians: [
    { id: "t1", name: "TS", fullName: "Tyler S." },
    { id: "t2", name: "JD", fullName: "Jane D." },
  ],
  equipment: [
    { id: "eq1", name: "Ice Machine", locationId: "l2" },
    { id: "eq2", name: "Walk-In Freezer", locationId: "l1" },
    { id: "eq3", name: "GCO", locationId: "l3" },
  ],
};

export const STATUS_OPTIONS = [
  "Unscheduled",
  "Scheduled",
  "In Progress",
  "Parts Needed",
  "Active",
  "Completed",
  "Cancelled",
];

export const STATUS_COLORS = {
  Unscheduled: "warning",
  "Parts Needed": "error",
  Active: "success",
  Scheduled: "primary",
  Completed: "default",
  "In Progress": "secondary",
  Cancelled: "default",
};

export const STATUS_HEX = {
  Unscheduled: "#f59e0b",
  "Parts Needed": "#ef4444",
  Active: "#22c55e",
  Scheduled: "#4f8ef7",
  Completed: "#6b7280",
  "In Progress": "#a855f7",
  Cancelled: "#6b7280",
};

export const REQUIRED_CUSTOMER_FIELDS = [
  { key: "contactName", label: "Contact Name" },
  { key: "email", label: "Contact Email" },
  { key: "phone", label: "Contact Phone" },
  { key: "billingAddress", label: "Billing Address" },
];

export const REQUIRED_LOCATION_FIELDS = [
  { key: "streetAddress", label: "Street Address" },
  { key: "city", label: "City" },
  { key: "state", label: "State" },
  { key: "zip", label: "ZIP Code" },
  { key: "phone", label: "Contact Phone" },
];

export const MONDAY_COLUMN_IDS = {
  CUSTOMERS: {
    EMAIL: "email_mm0rhasv",
    PHONE: "phone_mm0rpam7",
    ACCOUNT_NUMBER: "text_mm0ryhr9",
    STATUS: "color_mm0rjkns",
    BILLING_ADDRESS: "long_text_mm0r9ndz",
    BILLING_TERMS: "dropdown_mm0r9ywe",
    XERO_CONTACT_ID: "text_mm0rdxmk",
    XERO_SYNC_STATUS: "color_mm0rxh2b",
    NOTES: "long_text_mm0rppk5",
    WORK_ORDER: "board_relation_mm14w91d",
    LOCATIONS: "board_relation_mm18ma0k",
  },
  WORK_ORDERS: {
    CUSTOMER: "board_relation_mm14ngb2",
    LOCATION: "board_relation_mm14fdpt",
    DESCRIPTION: "long_text_mm14ee7h",
    STATUS: "color_mm14pf0q",
    TECHNICIAN: "multiple_person_mm14sesj",
    SCHEDULED_DATE: "date_mm14sjdg",
    MULTI_DAY: "boolean_mm14act2",
    MODEL: "lookup_mm19ygma",
    SERIAL_NUMBER: "lookup_mm19423v",
    SERVICE_HISTORY: "long_text_mm15p7rk",
    WORK_PERFORMED: "long_text_mm15kfzp",
    EQUIPMENT: "board_relation_mm19cxzv",
    PARTS_ORDERED: "color_mm1bs0w7",
    WORKORDER_ID: "text_mm1s82bz",
    EXECUTION_STATUS: "color_mm1s7ak1",
  },
  // Real Monday column IDs from the Locations board (id: 18400965227)
  LOCATIONS: {
    STREET_ADDRESS: "text_mm0r64n",
    CITY: "text_mm0rv9zr",
    STATE: "dropdown_mm0r9ajj",
    ZIP: "text_mm0rrexv",
    STATUS: "color_mm0rrea",
    NOTES: "long_text_mm0rns1x",
    WORK_ORDERS_REL: "board_relation_mm14vzq7",
    CUSTOMERS_REL: "board_relation_mm18fk7h",
    EQUIPMENTS_REL: "board_relation_mm19zxd8",
  },
};
